config/routes.rb
Rails.application.routes.draw do
  resources :cart
  get 'home/index'
  get '/resume', to: 'product#resume'
  get '/historique', to: 'product#past_orders'
  devise_for :users
  root to: "home#index"
  get '/test', to: 'test#test'
  post '/cart/checkout',  to:'cart#checkout'
  get '/empty', to: 'cart#empty'
  get '/show_orders/:id', to: 'product#toggle_past'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :product
  resources :charges
  get '/new_product', to: 'product#new'
  post 'product/new', to: 'product#create'
end

app/views/shared/_footer.html.erb
    <!-- Footer -->
      <div class="container">
        <p class="m-0 text-center text-dark">Copyright &copy; Groupe THP Grenoble 2018</p>
      </div>
      <!-- /.container -->
 

app/views/shared/_footerrelative.html.erb
    <!-- Footer -->
    <footer class="py-5 bg-dark" id="footer-relative">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Groupe THP Grenoble 2018</p>
      </div>
      <!-- /.container -->
    </footer>

app/views/shared/_modalin.html.erb
<div class="modal fade" id="modalIn" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Connexion</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "user@example.com" %>
          </div>

          <div class="field">
            <%= f.label :password %><br />
            <%= f.password_field :password, autocomplete: "current-password", placeholder: "Mot de passe" %>
          </div>

            <% if devise_mapping.rememberable? -%>
              <div class="field">
                <%= f.check_box :remember_me %>
                <%= f.label :remember_me %>
              </div>
            <% end -%>

            <div class="actions">
              <%= f.submit "Log in" %>
            </div>
          <% end %>

      </div>
      <div class="modal-footer d-flex justify-content-center">
        <a>Pas encore de compte ?</a>
        <a data-dismiss="modal" data-toggle="modal" href="#modalUp">Enregistre toi !</a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modalup.html.erb
<div class="modal fade" id="modalUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Création de compte</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>

          <div class="field">
            <%= f.label :username %><br />
            <%= f.text_field :username, autofocus: true, autocomplete: "username", placeholder: "user" %>
          </div>

          <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "user@example.com" %>
          </div>

          <div class="field">
            <%= f.label :password %>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "new-password", placeholder: "Min. 6 caractères"%>
          </div>

          <div class="field">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "new-password", placeholder: "Confirmation" %>
          </div>

          <div class="actions">
            <%= f.submit "Sign up" %>
          </div>
        <% end %>

      </div>
      <div class="modal-footer d-flex justify-content-center">
        <a>Tu as déjà un compte ?</a>
        <a data-dismiss="modal" data-toggle="modal" href="#modalIn">Connecte-toi !</a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top" style="background: rgba(131, 131, 130, 0.5)  !important;">
      <div class="container">
        <a class="navbar-brand" href="/"><img src="/assets/tele_logo.png" height="80" alt=""></a>
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a href="/product" class="nav-link">Nos produits</a>
            </li>
          </ul>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <% if current_user%>
                <% if current_user.admin?%>
                  <li class="collapse navbar-collapse">
                    <ul class="navbar-nav">
                      <li class="nav-item active">
                        <a class="nav-link" href="/resume">Toutes les commandes</a>
                      </li>
                      <li class="nav-item active">
                        <a class="nav-link" href="/historique">Mes commandes</a>
                      </li>
                      <li class="nav-item active">
                        <a class="nav-link" href="/cart">Mon panier</a>
                      </li>
                    </ul>

                    <li class="nav-item">
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navdrop" role="button" data-toggle="dropdown" data-hover="dropdown">Mon compte</a>
                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navdrop">
                          <%= link_to "Editer mon compte", edit_user_registration_path, :class=>"dropdown-item" %>
                          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, :class=>"dropdown-item" %>
                          </div>
                      </li>
                    </li>
                  </li>
            
            <% else user_signed_in? %>
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a href="/cart" class="nav-link">Mon panier</a>
                </li>
              </ul>
              <li class="nav-item">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" id="navdrop" role="button" data-toggle="dropdown" data-hover="dropdown">Mon compte</a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navdrop">
                      <a class="dropdown-item" href="/historique">Mes commandes</a>
                      <a><%= link_to "Editer mon compte", edit_user_registration_path, :class=>"dropdown-item" %></a>
                      <a><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, :class=>"dropdown-item" %></a>
                    </div>
                </li>
              </li>
            <% end %>

            <% else %>
            <li class="nav-item">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navdrop" role="button" data-toggle="dropdown" data-hover="dropdown">Mon compte</a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navdrop">
                    <a class="dropdown-item" data-toggle="modal" href="#modalIn">Se connecter</a>
                    <a class="dropdown-item" data-toggle="modal" href="#modalUp">S'enregistrer</a>
                  </div>
              </li>
            </li>

            <% end %>
          </ul>
        </div>
      </div>
    </nav>