config/routes.rb
Rails.application.routes.draw do
  resources :cart
  get 'home/index'
  get '/resume', to: 'product#resume'
  get '/historique', to: 'product#past_orders'
  devise_for :users
  root to: "home#index"
  get '/test', to: 'test#test'
  post '/cart/checkout',  to:'cart#checkout'
  get '/empty', to: 'cart#empty'
  get '/show_orders/:id', to: 'product#toggle_past'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :product
  resources :charges
  get '/new_product', to: 'product#new'
  post 'product/new', to: 'product#create'
end

app/views/layouts/_bouton_homepage.html.erb
                   <!-- BOUTON -->
                  <div class="row middle-on-small center-on-small">
                  <div class="column small-12 medium-6 large-4">
                  <a href="/product.html" class="c-button c-button--gooey">
                  Voir les photos
                  <div class="c-button__blobs">
                  <div></div>
                  <div></div>
                  <div></div>
                  </div>
                  </a>
                  </div>
                  </div>

                  <svg xmlns="http://www.w3.org/2000/svg" version="1.1" style="display: block; height: 0; width: 0;">
                  <defs>
                  <filter id="goo">
                  <feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur"></feGaussianBlur>
                  <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo"></feColorMatrix>
                  <feBlend in="SourceGraphic" in2="goo"></feBlend>
                  </filter>
                  </defs>
                  </svg>
                  <!-- FIN DU BOUTON -->

app/views/layouts/_content_admin.html.erb
<%if @amount != 0%>
<h3>Nous avons gagné <%=@amount%>$ avec <%=@orders.count%> de commandes 
    <br/>
    Cela représente <%= @amount / @orders.count%>$ par commande !!!!
</h3>

<h3>Nous avons <%= @users.count%> visiteurs, qui ont commandé en moyenne <%= @orders.count/@users.count%> commandes </h3>

<h3>Historique des commandes</h3>
<table class="table" style="color: black;">
  <thead>
	  <tr>
      <td>N° de commande</td>
      <td>Réalisée par</td>
	  	<td>Prix</td>
      <td>Contenu de la commande</td>
      <td>Date</td>
		</tr>
	</thead>
  <tbody>
  <%if @orders%>
    <% @orders.each do |order| %>
	    <tr id='element_<%=order.id%>', remote: true>
        <td>Commande <%=order.id%></td>
		    <td> <%=order.user.email%> </td>
		    <td><%= order.price  %></td>
        <td><p>
        <%order.items.each_with_index do |item, index|%>
        <%=order.quantities[index]%> x <%= item.title  %>, 
        <%end%>
        </p> </td>
			  <td><%=order.created_at%></td>
	    </tr>
    <% end %>
  <% end %>
  </tbody>
</table>
<%else%>
<h2>Personne n'a encore commandé</h2>
<%end%>

app/views/layouts/_content_cart.html.erb
<table class="table" style="color: white;">
  <thead>
	  <tr>
      <td>Chat trop mignon</td>
      <td>Nom du chat trop mignon</td>
	  	<td>Photographié par :</td>
      <td>Quantité dans le panier</td>
			<td></td>
		</tr>
	</thead>
  <tbody id = "<%=@cart.id%>">
  <%if @content%>
    <% @content.each_with_index do |item, index| %>
	    <tr id='element_<%=item.id%>', remote: true>
        <td><img class="avatar" width="200" height="120" class="card-img-top"  src='<%=item.image_url%>'></td>
		    <td><%= item.title %></td>
		    <td><%= item.description  %></td>
        <td>
        <div class="d-flex flex-row align-items-center justify-content-center">
          <%= link_to " - ", cart_path(@cart, :id_modify => item.id, :increase => false), class: "btn btn-sm btn-success", remote: true,  method: :patch%>
          &nbsp;<%= @cart.quantities[index]%>&nbsp;
          <%= link_to " + ", cart_path(@cart, :id_modify => item.id, :increase => true), class: "btn btn-sm btn-success", remote: true,  method: :patch%>
        </div>
        </td>
			  <td><%= link_to " Delete", cart_path(@cart, :id_delete => item.id), class: "btn btn-sm btn-danger bouton-d far fa-trash-alt", remote: true,  method: :delete, data: { confirm: "Are you sure?" } %></td>
	    </tr>
    <% end %>
  <% end %>
  </tbody>
</table>
<p id="price">Votre total actuel est de <%=@price%> $</p>

<% if @price !=0 %>
  <div class="row justify-content-between">
    <div class="col-6" >
      <%= link_to "Vider le panier", "/empty", class: "btn btn-sm btn-warning bouton-d far fa-trash-alt" %>
    </div>
    <div class="col-6">
        <%= link_to "Payer", "/charges/new", class: "btn btn-lg btn-info bouton-d far fa-trash-alt" %>
    </div>
  </div>
<% end %>

</div>
<p>&nbsp;</p>
    

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
<% end %>

app/views/layouts/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  

 <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.label :description %>
    <%= form.text_field :description %>
    <%= form.label :price %>
    <%= form.text_field :price %>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/_hist_order.html.erb
<div class = 'card card-tot d-flex flex-column'>
  <h2>Commande <%=@order.id%></h2>
  <p>&nbsp;</p>
	<h4>Vous avez payé <%= @order.price  %> $</h4>
  <h4> La commande contient :</h4>
  <div class = "d-flex flex-wrap justify-content-center">
  <%@order.items.each_with_index do |item, index|%>
    <div id='item_<%index%>' class =' col-3 d-flex flex-row align-items-center card card-command'>
      <img width="90" height="75" class="card-img-top" src='<%=item.image_url%>' alt="">
      <p><%=@order.quantities[index]%> x <%= item.title  %></p>
    </div>&nbsp;
  <%end%>
  </div>
  <p>&nbsp;</p>
	<h4> <br/>Date de la commande: <%=@order.created_at%></h4>
</div>

app/views/layouts/_list.html.erb
<ul class = "Commandes">
<% @orders.each do |order| %>
    <li class='orders'>
    <%= link_to "Commande #{order.id}", "/show_orders/#{order.id}", class: 'show list-group-item list-group-item-action', id: order.id, remote: true %>
    </li>
<% end %>
</ul>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="shortcut icon" type="image/x-icon" href="/assets/logo_cat.png">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Télé à Chat</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div class="wrapper">
      <%= render "shared/navbar" %>
      <%= render 'shared/modalin'  %>
      <%= render 'shared/modalup'  %>
      

      <div class ="rendering">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
      </div>


    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <footer class="footer">
      <%= render 'shared/footer' %>
    </footer>

  </body>
</html>